package tama;

public enum Estado {
    FELIZ, HAMBRIENTO, CANSADO, TRISTE, SUCIO, NECESITA_MEDICINA, SOBREPESO, DESNUTRIDO, DEBIL, ENFERMO, NECESITA_CACA, QUIERE_JUGAR, TIENE_SUEÑO, INQUIETO, NORMAL
}